/*********
 * This file is autogenerated by generate_base.py.
 * Please don't modify it manually.
 *********/

#ifndef base_h
#define base_h

#include <stdint.h>
#include <inttypes.h>

typedef uint64_t fixed;

#define FIX_PRINT_BUFFER_SIZE 43

#define FIX_PRINTF_HEX "%016"PRIx64
#define FIX_PRINTF_DEC "%"PRId64

#define FIX_FLAG_BITS 2
#define FIX_FRAC_BITS 30
#define FIX_INT_BITS  32
#define FIX_BITS (8*sizeof(fixed))

#define FIX_INTERN_FRAC_BITS 60
#define FIX_INTERN_INT_BITS 4

static const fixed fix_pi = 0x00000003243f6a88;
static const fixed fix_tau = 0x00000006487ed510;
static const fixed fix_e = 0x00000002b7e15164;

#define FIX_PI fix_pi
#define FIX_TAU fix_tau
#define FIX_E fix_e

#endif